#!/usr/bin/env perl

use open IN => ':encoding(UTF-8)';
binmode STDIN, ':encoding(UTF-8)';
binmode STDOUT, ':utf8';

print "digraph Wikisophy {\n";
print "\tnode [shape=box];\n";

while (<>) {
	s/^/\t"/;
	s/#/" -> "/;
	s/$/";/;
	y/_/ /;
	$_ = lc;

	print;
}

print "}\n";
