#!/usr/bin/env perl

use open IN => ':encoding(UTF-8)';
binmode STDIN, ':encoding(UTF-8)';
binmode STDOUT, ':utf8';

print "digraph Wikisophy {\n";
print "\tnode [shape=box];\n";

while (<>) {
	s/^([^#]+)#(.*)$/\t"\u$1" -> "\u$2";/;
	y/_/ /;

	print;
}

print "}\n";
