#!/usr/bin/env perl
use strict;
use warnings;

use LWP::Simple;
use Text::Balanced qw(extract_bracketed);

my $pagename = $ARGV[0];

while (1) {
	print "-> $pagename\n";

	if(lc($pagename) eq "philosophy") {
		print "  QED\n";
		last;
	}

	if (lc($pagename) ~~ ["physics", "mathematics", "science"]) {
		print "  QED (terminated early)\n";
		last;
	}

	my $c = get("https://secure.wikimedia.org/wikipedia/en/wiki/$pagename?action=raw");

	wikiparse: while (length($c)) {
		if (defined($ARGV[1]) and $ARGV[1] eq "debug") {
			print $c;
			print "*" x 80 . "\n\n";
		}

		$c =~ s/<ref>.*?<\/ref>//gs;
		$c =~ s/'''?[^\n]'''?//s;

		if ($c =~ /^[^{(]+\[\[/s) {
			$c =~ s/^[^\[]+//s;
			($pagename, $c) = extract_bracketed($c);

			$pagename =~ s/^\[\[//;
			$pagename =~ s/\]\]$//;
			$pagename =~ s/\|.*//;

			if ($pagename =~ /:/) {
				next wikiparse;
			}

			last wikiparse;
		} else {
			$c =~ s/^[^{(]+//s;
			(undef, $c) = extract_bracketed($c);
		}
	} 
}

